server:
  port: 8081

spring:
  #DATABASE
  datasource:
    url: jdbc:postgresql://localhost:5432/jpadatabase
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret:
    key: 48a868a4042f634ac04a117f00a87202131dd7c46c4b32c4acb3edc5e15f4511
  expiration:
    ms: 3600000